# Generated by Django 4.0.5 on 2022-07-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BooksApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('BookShelfId', models.AutoField(primary_key=True, serialize=False)),
                ('books', models.ManyToManyField(to='BooksApp.book')),
            ],
        ),
    ]
