# Generated by Django 4.0.5 on 2022-07-23 21:47

import BooksApp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=500)),
                ('BookAuthor', models.CharField(max_length=500)),
                ('BookCover', models.ImageField(blank=True, null=True, upload_to=BooksApp.models.upload_path)),
                ('Synopsis', models.TextField(max_length=2000)),
                ('Rating', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('BookGenre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BooksApp.genres')),
            ],
        ),
    ]
