# Generated by Django 4.0.5 on 2022-07-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='BookCover',
            field=models.ImageField(blank=True, null=True, upload_to='media\x08ookcovers'),
        ),
    ]
