# Generated by Django 4.0.5 on 2022-07-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_rename_genres_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookGenre',
        ),
        migrations.AddField(
            model_name='book',
            name='BookGenre',
            field=models.ManyToManyField(to='BooksApp.genre'),
        ),
    ]
