# Generated by Django 4.0.5 on 2022-07-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0004_alter_books_bookcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='BookCover',
            field=models.ImageField(blank=True, null=True, upload_to='bookworms/media/bookcovers'),
        ),
    ]
