# Generated by Django 4.0.5 on 2022-07-11 18:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0013_alter_books_bookcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='BookCover',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/bookcovers'), upload_to=''),
        ),
    ]
