# Generated by Django 4.0.5 on 2022-07-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0014_alter_books_bookcover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=500)),
                ('BookCover', models.ImageField(blank=True, null=True, upload_to='bookcovers')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
