# Generated by Django 4.0.5 on 2022-07-11 23:15

import BooksApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0015_book_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookCover',
            field=models.ImageField(blank=True, null=True, upload_to=BooksApp.models.upload_path),
        ),
    ]
