# Generated by Django 4.0.5 on 2022-07-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClubsApp', '0001_initial'),
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bookclubs',
            field=models.ManyToManyField(null=True, to='BookClubsApp.bookclub'),
        ),
    ]
