# Generated by Django 4.0.5 on 2022-07-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsApp', '0002_rename_booktitle_review_reviewtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
