# Generated by Django 4.0.5 on 2022-07-22 20:04

import BookClubsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=500)),
                ('BookCover', models.ImageField(blank=True, null=True, upload_to=BookClubsApp.models.upload_path)),
                ('GroupComment', models.TextField()),
                ('Comment', models.CharField(max_length=500)),
            ],
        ),
    ]
